- gravity/commands/cmd_start.py
- gravity/config_manager.py
- gravity/process_manager/__init__.py
- gravity/process_manager/supervisor_manager.py
- Use `$GALAXY_ROOT_DIR` and `$GALAXY_CONFIG_FILE`
- Refactor auto-registration on `galaxy`/`galaxyctl start`
- Fail to start with a useful error if no configs are registered
> Better integration with Galaxy's run.sh

- gravity/config_manager.py
@dannon immediately ran into this after the merge of the Gravity PR to Galaxy. I guess we will have to release a 0.9.1 version and PR that to Galaxy... Hopefully there aren't a ton of these. I guess the Galaxy startup tests don't exactly cover a ton of cases.
> Fix for the case where a job_conf.xml exists but no handlers are defined

- gravity/config_manager.py
Fix for starting Galaxy with the sample config file which can have
all options commented out, which presently errors with:
```
Config file /srv/galaxy/config/galaxy.yml.sample does not look like valid Galaxy, Reports or Tool Shed configuration file
```
See e.g.:
https://github.com/galaxyproject/galaxy/runs/5019325678?check_suite_focus=true#step:11:1662
> Do not raise error if config file section is empty

- .github/workflows/publish.yaml
We'll publish to test.pypi.org when creating a tag, and to pypi.org when
creating a release.
> Add setup for publishing to PyPI

- gravity/settings.py
The default is `log` not `logs`, see https://github.com/galaxyproject/gravity/blob/f4c73ae92a4301b4c4967494bfe413f0e22d14c3/gravity/config_manager.py#L80
> Fix typo in ``log_dir`` description

- gravity/commands/cmd_follow.py
- gravity/commands/cmd_graceful.py
- gravity/commands/cmd_restart.py
- gravity/commands/cmd_start.py
- gravity/commands/cmd_stop.py
- gravity/process_manager/__init__.py
- gravity/process_manager/supervisor_manager.py
Technically the control subcommands (`start`, `stop`, `restart`, etc.) take a list of instances as arguments, but we do a lot of shortcutting if there is only one instance registered, which is the common case.  In this case, if the instance arg is actually a service for that instance, we perform the desired operation just for that service. e.g.
```console
$ galaxyctl restart gunicorn
```
is a shortcut for:
```console
$ galaxyctl supervisorctl restart gunicorn
```
Except it didn't work due to a bug,  which this PR fixes.
Draft for a moment because I realized I should make the help explain that.
> Shortcut individual services fix

- gravity/settings.py
- gravity/state.py
Shouldn't be necessary for the others since everything else would typically be installed in the venv. `tusd` could be as well if you choose.
> Add option to specify tusd path

- gravity/config_manager.py
- gravity/process_manager/__init__.py
- gravity/process_manager/supervisor_manager.py
- gravity/settings.py
- gravity/state.py
This allows you to set environment variables on a per-service basis using the `environment` key of a setting, e.g.:
```yaml
gravity:
gunicorn:
environment:
FOO: bar
PYTHONPATH: lib:/path/to/dynamic/rules
```
Unfortunately, you cannot *unset* a var because they get saved in the configstate, but updating the value of a set var does update its value in the supervisor config.
> Support setting per-service environment variables

- gravity/commands/cmd_deregister.py
- gravity/commands/cmd_register.py
- gravity/commands/cmd_rename.py
Doing so loses the traceback, making it a lot harder to debug. Also, `gravity.io.exception()` doesn't take any args beyond the message string.
> Don't catch exceptions in the deregister, register, and rename subcommands

- gravity/config_manager.py
- tests/test_process_manager.py
Should fix the test error in galaxyproject/galaxy#13995:
```pytb
Traceback (most recent call last):
1056
File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/gravity/commands/cmd_register.py", line 18, in cli
1057
cm.add(config)
1058
File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/gravity/config_manager.py", line 418, in add
1059
conf = self.get_config(config_file, defaults=defaults)
1060
File "/home/runner/work/galaxy/galaxy/galaxy root/.venv/lib/python3.7/site-packages/gravity/config_manager.py", line 143, in get_config
1061
for service_name in [x["service_name"] for x in ConfigManager.get_job_config(job_config) if x["service_name"] not in webapp_service_names]:
1062
File "/home/runner/work/galaxy/galaxy/galaxy …
```
> `processes` in the `handling` dict in the job conf dict is a dict, not a list

- tests/conftest.py
When `env` is set in the call to `subprocess`, the `PATH` env variable will be overwritten.
(as per docs: "...If env is not None, it must be a mapping that defines the environment variables for the new process; these are used instead of the default behavior of inheriting the current process’ environment.")
As a  result, if the `virtualenv` command is not in `/usr/local/bin` or `/urs/bin` (I had it in `~/.local/bin/`), the `galaxy_virtualenv` fixture will (silently!) not create the virtual environment. Passing the path explicitly should fix this use case.
> Don't override PATH in subprocess call

- gravity/state.py
use Galaxy's python logging config instead, so that rotation can be performed.
Rotation depends on galaxyproject/galaxy#14457 unless you do a full custom logging config, and the access log entries will be missing from the gunicorn log file (when running under unicornherder) without galaxyproject/galaxy#14467, so this should not be tagged and released until after those are merged.
If you need to set the `log_destination` Galaxy config option from the environment, you can use `$GALAXY_CONFIG_OVERRIDE_LOG_DESTINATION`.
> Don't use gunicorn logging options with unicornherder

- README.rst
- gravity/config_manager.py
- gravity/state.py
- tests/test_config_manager.py
- tests/test_process_manager.py
Tested on both `job_conf.yml` and Gravity config, works on the inline `job_config` as well.
Fixes #61.
> Fix setting environment vars on handlers

- gravity/process_manager/supervisor_manager.py
- gravity/state.py
This doesn't appear if Gravity is installed in your Galaxy venv and the venv is activated when supervisord launches, but is necessary when they are separate.
> If virtualenv is set in the Gravity config, automatically add its bin dir to $PATH if the gx-it-proxy is enabled

- gravity/config_manager.py
- gravity/process_manager/supervisor_manager.py
- gravity/state.py
It's easy to include Gravity config setting values in the command line template, but only direct value substitutions with minor formatting since the command template is a `str.format()` string, not an f-string. And even if they were f-strings, putting a lot of logic inside the command template string is probably not ideal... So at present, you can't use settings to control the presence of optional flags in the command line. This allows you to do so, and fixes the documented-but-unimplemented `forward_*` and `reverse_proxy` gx-it-proxy settings (fixes #67).
As noted in the FIXME comment, to make an assumption based on the truthiness of the settings value is maybe not the best method for determining whether an optional should be replaced with its `command_arguments` value. Maybe the …
> Support converting settings to command line arguments in a generalized way

- gravity/cli.py
It'd be useful to get the Galaxy version as well, I'm adding that in the 1.x branch though.
> Add --version option to get Gravity version

- README.rst
- gravity/commands/cmd_exec.py
- gravity/commands/cmd_start.py
- gravity/commands/cmd_status.py
- gravity/config_manager.py
- gravity/io.py
- gravity/process_manager/__init__.py
- gravity/process_manager/supervisor.py
- gravity/process_manager/systemd.py
- gravity/settings.py
- gravity/state.py
- gravity/util/__init__.py
- setup.py
- tests/test_process_manager.py
This should alleviate the need for unicornherder or gunicorn `SIGUSR2`-based solutions to zero downtime restarts. usegalaxy.eu is already using this in production, albeit without Gravity. This change allows Gravity to perform the restart using `galaxyctl graceful`.
I also changed repeating services (so, multiple gunicorns and multiple dynamic handlers under the same name in the Gravity config) to use service instances - `numprocs` in supervisord and `unit@.service` in systemd. This isn't strictly required but it's maybe a nice feature for keeping things organized.
Although one of the benefits you could get from service instances isn't possible: namely, if you have `N` handlers configured, you might imagine adding additional handlers with `systemctl start galaxy-handler@N+1.service`, but …
> Multi-unicorn rolling restart and general multi-instance service support

- gravity/process_manager/__init__.py
- gravity/process_manager/systemd.py
For galaxyproject/galaxy#15017
> Fixes for spaces in the galaxy root path, fix the `galaxy` entrypoint

- README.rst
- gravity/settings.py
- gravity/util/__init__.py
As [discussed here](https://github.com/galaxyproject/galaxy/pull/15017#discussion_r1039892985)
> Hide the "exec" ServiceCommandStyle from documentation since it is only used internally

- gravity/state.py
The Galaxy job wrapper depends on this being set in order to set up the env for `metadata/set.py`
> Set `$VIRTUAL_ENV` if `virtualenv` is set in config

- docs/installation.rst
- gravity/settings.py
- gravity/state.py
- tests/test_process_manager.py
As @sveinugu pointed out in #96, not forcing the version to update will cause startup failures on existing Galaxy servers since older versions of the proxy do not have the new `--proxyPathPrefix` flag.
> Pin a minimum package version of gx-it-proxy

- gravity/process_manager/supervisor.py
This is a follow-up to #110, removing the unneeded call to `update` command
Not sure if `reread` is needed in fact, maybe supervisor already watches changes to these config files? :thinking:
> Remove unneeded supervisorctl update call

- docs/installation.rst
- gravity/settings.py
- gravity/state.py
- tests/test_process_manager.py
Also requires new version 0.0.6 of gx-it-proxy (galaxyproject/gx-it-proxy#17).
Should result in a new release 1.0.4 after merge (as required by galaxyproject/galaxy#16795). @natefoo?
Replaces https://github.com/elixir-oslo/gravity/pull/2 which was within my own repo and just stupid! 😅
> Minimal path change needed for galaxy PR 16795

- gravity/commands/cmd_list.py
- gravity/config_manager.py
- gravity/process_manager/__init__.py
- gravity/process_manager/supervisor.py
- gravity/process_manager/systemd.py
- gravity/state.py
- tests/test_config_manager.py
- tests/test_operations.py
- tests/test_process_manager.py
Hello,
This fix #115.  
In addition it also make the _ConfigFile_ class more robust by catching exceptions in the constructor; they were ignored previously. 
Finally, it delete the _config_type_  in both _ConfigFile_ and _Service_ classes. Firstly because it wasn't copied properly  in the _Service_ class constructor (the error was silent due to the previous issue), secondly because it has no current use. 
I tested the supervisor configuration locally but not the systemd one.
> Fix GalaxyReportsService crash and remove config_type

- gravity/settings.py
- gravity/state.py
Now that you can use tusd with job_files uploads, provide a way to run multiple tusds from gravity
> Support running multiple tusds and controlling the value of hooks-http

- .github/workflows/lint.yaml
- .github/workflows/package.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
- gravity/cli.py
- gravity/config_manager.py
- gravity/options.py
- gravity/process_manager/__init__.py
- gravity/process_manager/systemd.py
This is useful for example if you want to use Gravity to do a restart as a non-root user that has privileges to do so via PolicyKit.
> Add a command line flag for controlling systemd user mode

- docs/installation.rst
- gravity/settings.py
- gravity/state.py
At the moment, the Gravity setting `sessions` is "overridden" with `interactivetools_map` if configured in the Galaxy settings.
A new Galaxy setting `interactivetoolsproxy_map` was added in galaxyproject/galaxy#18481 that overrides interactivetools_map` if defined. Gravity should do the same. This PR also documents the change.
> Support new Galaxy configuration setting `interactivetoolsproxy_map`

- gravity/state.py
- tests/test_process_manager.py
Recently, the `gx-it-proxy` npm package has been moved to the `@galaxyproject` namespace, where v.0.2.2 is now [published](https://www.npmjs.com/package/@galaxyproject/gx-it-proxy).
However, Gravity still is configured to run `npx install gx-it-proxy` instead of `npx install @galaxyproject/gx-it-proxy`, which still [refers to the old version](https://www.npmjs.com/package/gx-it-proxy).
This PR updates the `npx` command.
For more context, see https://github.com/galaxyproject/gx-it-proxy/issues/25
> Update interactive tool command to reflect new package namespace

- gravity/cli.py
- gravity/config_manager.py
- gravity/io.py
- gravity/options.py
- gravity/process_manager/__init__.py
- gravity/process_manager/multiprocessing.py
- gravity/settings.py
- gravity/state.py
Once the galaxy metapackage is published w/ galaxy-web-client, this allows you to:
```console
$ pip install galaxy
$ galaxy
```
The addition of multiprocessing removes the need for any state and log file handling for the simplest case of just starting Galaxy in the foreground.
> Rootless processmanagerless mode
